# Generated by Django 5.1.6 on 2025-02-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0006_report_commands_report_dns_report_files_report_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='syscalls',
            field=models.JSONField(default=list),
        ),
    ]
