# Generated by Django 5.1.6 on 2025-02-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='package_analysis.package'),
        ),
    ]
