# Generated by Django 5.1.6 on 2025-02-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0005_remove_report_commands_remove_report_domains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='commands',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='dns',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='files',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='ips',
            field=models.JSONField(default=list),
        ),
    ]
