# Generated by Django 5.1.6 on 2025-04-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0007_report_syscalls'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='typosquatting_candidates',
            field=models.JSONField(default=list),
        ),
    ]
