# Generated by Django 5.1.6 on 2025-04-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0008_report_typosquatting_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='source_url',
            field=models.JSONField(default=list),
        ),
    ]
