# Generated by Django 5.1.6 on 2025-02-18 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0002_alter_report_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='package_analysis.package'),
        ),
    ]
