# Generated by Django 5.1.6 on 2025-02-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0003_alter_report_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='commands',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='domains',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='files',
            field=models.JSONField(default=dict),
        ),
    ]
