# Generated by Django 5.1.6 on 2025-02-19 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0004_report_commands_report_domains_report_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='commands',
        ),
        migrations.RemoveField(
            model_name='report',
            name='domains',
        ),
        migrations.RemoveField(
            model_name='report',
            name='files',
        ),
    ]
