# Generated by Django 5.1.6 on 2025-04-17 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0009_report_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDynamicAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('num_files', models.IntegerField()),
                ('num_commands', models.IntegerField()),
                ('num_network_connections', models.IntegerField()),
                ('num_system_calls', models.IntegerField()),
                ('files', models.JSONField(default=dict)),
                ('dns', models.JSONField(default=list)),
                ('ips', models.JSONField(default=list)),
                ('commands', models.JSONField(default=list)),
                ('syscalls', models.JSONField(default=list)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_dynamic_analysis', to='package_analysis.package')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.JSONField(default=list)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_source', to='package_analysis.package')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTyposquatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typosquatting_candidates', models.JSONField(default=list)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_typosquatting', to='package_analysis.package')),
            ],
        ),
    ]
