# Generated by Django 5.1.6 on 2025-04-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0010_reportdynamicanalysis_reportsource_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='report',
            name='typosquatting_candidates',
        ),
    ]
